# Generated by Django 5.2.3 on 2025-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_galeria/')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albumes',
                'db_table': 'album',
            },
        ),
    ]
