# Generated by Django 5.2.3 on 2025-09-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagen',
        ),
    ]
