# Generated by Django 5.2.3 on 2025-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('visitas', models.IntegerField(default=0)),
            ],
        ),
    ]
