# Generated by Django 5.2.3 on 2025-06-26 13:50

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_programa', models.ImageField(upload_to='prog_forma/')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo')),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
