# Generated by Django 5.2.3 on 2025-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_forma', '0001_initial'),
        ('usuarios', '0004_alter_usuario_fecha_nacimiento_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='programas', to='usuarios.usuario'),
        ),
    ]
