# Generated by Django 5.2.3 on 2025-08-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_forma', '0002_programa_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AddField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[('ece', 'Artes escénicas'), ('visu', 'Artes visuales')], default='ece', max_length=4),
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
    ]
