# Generated by Django 5.2.3 on 2025-08-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog_forma', '0003_alter_programa_options_programa_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={},
        ),
        migrations.RemoveField(
            model_name='programa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='usuarios',
        ),
        migrations.AlterModelTable(
            name='programa',
            table=None,
        ),
    ]
