# Generated by Django 5.2.3 on 2025-06-25 22:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombre'),
        ),
    ]
