# Generated by Django 5.2.3 on 2025-07-02 13:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombre', verbose_name='Nombre de usuario'),
        ),
    ]
