# Generated by Django 5.2.3 on 2025-07-02 14:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=100, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombre'),
        ),
    ]
