# Generated by Django 5.2.3 on 2025-08-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='auth_user',
        ),
    ]
