# Generated by Django 5.2.3 on 2025-07-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposicion',
            options={'verbose_name': 'Exposicion', 'verbose_name_plural': 'Exposiciones'},
        ),
        migrations.AlterModelTable(
            name='exposicion',
            table='exposicion',
        ),
    ]
