# Generated by Django 5.2.3 on 2025-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposiciones', '0002_alter_exposicion_options_alter_exposicion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposicion',
            options={},
        ),
        migrations.RemoveField(
            model_name='exposicion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='exposicion',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='exposicion',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='exposiciones/'),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='exposicion',
            table=None,
        ),
    ]
