# Generated by Django 5.2.3 on 2025-06-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Inventario',
        ),
    ]
