# Generated by Django 5.2.3 on 2025-06-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_categoria_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
