# Generated by Django 5.2.3 on 2025-06-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_descripcion_alter_inventario_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
