# Generated by Django 5.2.3 on 2025-06-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(upload_to='inventario/'),
        ),
    ]
