# Generated by Django 5.2.3 on 2025-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/'),
        ),
    ]
