# Generated by Django 5.2.3 on 2025-07-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposiciones', '0001_initial'),
        ('inventario', '0006_alter_inventario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='exposicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exposiciones.exposicion'),
        ),
    ]
