# Generated by Django 5.2.3 on 2025-07-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_inventario_exposicion'),
        ('usuarios', '0004_alter_usuario_fecha_nacimiento_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
